#ifndef POWER_PLANTS_H
#define POWER_PLANTS_H

#include "Utilities.h"

/**
 * @class PowerPlants
 * @brief Represents a utility for generating and supplying electricity to buildings.
 * 
 * The PowerPlants class is responsible for managing power generation and consumption,
 * ensuring that buildings receive the necessary electricity for operation.
 */
class PowerPlants : public Utilities {
private:
    int powerGenerated; ///< Total amount of power generated by the power plant.
    int powerConsumed;  ///< Amount of power consumed by buildings connected to the power plant.

public:
    /**
     * @brief Constructs a PowerPlants instance.
     * 
     * @param bld Pointer to the associated Building.
     * @param rf Pointer to the ResourceFactory for managing resources.
     * @param cost Cost required to construct the power plant.
     */
    PowerPlants(Building *bld, ResourceFactory *rf, float cost, int capacity);

    /**
     * @brief Applies the utility of the power plant to the specified building.
     * 
     * This method checks for power availability and supplies electricity to the building if possible.
     * 
     * @param building Pointer to the Building that requires electricity.
     */
    void applyUtility(Building* building) override;

    /**
     * @brief Checks if there is sufficient power available for consumption.
     * 
     * @return True if enough power is available, otherwise false.
     */
    bool checkPowerAvailability() const;

    /**
     * @brief Updates the power generation of the power plant.
     * 
     * @param additionalPower The amount of additional power to be added to the generated power.
     */
    void updatePowerGeneration(int additionalPower);

    // Getters
    /**
     * @brief Retrieves the total power generated by the power plant.
     * 
     * @return Total power generated.
     */
    int getPowerGenerated() const { return powerGenerated; }

    /**
     * @brief Retrieves the total power consumed by the power plant.
     * 
     * @return Total power consumed.
     */
    int getPowerConsumed() const { return powerConsumed; }
};

#endif
